<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Selesi_verifyTheme</name>
   <tag></tag>
   <elementGuidId>4422eecc-8e04-4e39-bb1d-b61d51c16742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-outer&quot;]/div/div/div/div[3]/div[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>7f339999-4e46-4f45-893b-1fd557bb972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-outer&quot;]/div/div/div/div[3]/div[5]/button</value>
      <webElementGuid>e1ceb312-fdeb-470c-896f-1cde862614a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
