<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yahoo Mail_select-input react-typeahe_333923</name>
   <tag></tag>
   <elementGuidId>0d81b194-6225-44c0-ba11-ba779d145031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.select-input.react-typeahead-input.k_w.W_6D6F.P_Z1E2YFn.i_6LEV.M_0.b_0.A_6EWk.c1AVi73_6FYl.c1AVi7H_6Mrc.y_Z2hYGcu.I_T.p_R.Z_N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67e13589-6f96-42d9-98a1-4261547c013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9b90ea4b-3884-4d57-a906-e920165ee756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>127a11ec-4ecf-4027-814b-7454c0636d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6310dfba-c88a-4c17-b781-5468e53d5ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Kotak pencarian. Temukan pesan, dokumen, foto, atau orang</value>
      <webElementGuid>1815f00f-cf9e-41d2-a892-aa99fcb06990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input react-typeahead-input k_w W_6D6F P_Z1E2YFn i_6LEV M_0 b_0 A_6EWk c1AVi73_6FYl c1AVi7H_6Mrc y_Z2hYGcu I_T p_R Z_N</value>
      <webElementGuid>5ba80d86-4ef1-434a-8870-af9767a9d0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Temukan pesan, dokumen, foto, atau orang</value>
      <webElementGuid>b0a12008-5096-462c-a739-b5d83a83c5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4d404f49-d299-4a2c-916d-620feb74d6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>dbbf039c-5f3e-4ecc-aa52-122f9d6db74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17ce4f92-257d-4e9f-addd-c60365dfd83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44e3b1b2-1f5d-4544-b84c-bc0beb4e57c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33afe8d3-c1c7-44fe-8e51-0f9fa50872d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c53284a0-6636-466c-be68-55700fda3865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb67df1c-c297-4ac4-a358-1f1ffc1000ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>f992e983-3501-4863-b999-d880f28cbf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e5f1255b-0fc7-4ccf-8b99-65919891b588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail-search&quot;)/div[@class=&quot;D_F en_0 H_74JI p_R&quot;]/div[@class=&quot;D_F W_6D6F b_9EMiX s_3z5BY cj_eo6 bk_eo6 k_w I_ZkbNhI p_R&quot;]/div[@class=&quot;react-y-pills k_w D_F ab_C W_1BJksS p_s s_3v1qi is-focused&quot;]/ul[@class=&quot;pill-list hd_n em_N eo_x el_EZ D_F M_0 P_3HLUz ir_0 o_A K_3qWeB&quot;]/li[@class=&quot;pill-container em_N o_h s_3nx4N&quot;]/div[@class=&quot;select is-focused&quot;]/div[@class=&quot;typeahead-inputs-container p_R&quot;]/input[@class=&quot;select-input react-typeahead-input k_w W_6D6F P_Z1E2YFn i_6LEV M_0 b_0 A_6EWk c1AVi73_6FYl c1AVi7H_6Mrc y_Z2hYGcu I_T p_R Z_N&quot;]</value>
      <webElementGuid>7b990a34-7386-46b0-b6ca-1a5f7d47dba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>cd5cdb09-8133-40f7-a9a6-da353191516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail-search']/div/div/div/ul/li/div/div/input</value>
      <webElementGuid>1cc36a23-06ca-4af5-b5e2-b494fc677332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f6962f0a-92ff-4b7f-b061-df005f2efa67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Temukan pesan, dokumen, foto, atau orang' and @type = 'text']</value>
      <webElementGuid>e58a04d8-7916-4b93-845e-526a48e3e66c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
