<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_2431</name>
   <tag></tag>
   <elementGuidId>5cf17179-3f0e-4b7b-92cb-00d646c1e2a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td/div[2]/div[2]/div/div[3]/div[1]/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[1]/div[1]/div[1]/table[2]/tbody/tr[3]/td/p</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c7c235c7-b09e-47c9-80d2-9ab84f8e601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        2431
                    </value>
      <webElementGuid>081384d2-bca8-4e8b-ad9b-10910e4f23c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:6o&quot;)/div[1]/div[1]/div[1]/table[2]/tbody[1]/tr[3]/td[1]/p[1]</value>
      <webElementGuid>9d3ffd99-3ec3-4280-b76c-1f2cba4631d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':6o']/div/div/div/table[2]/tbody/tr[3]/td/p</value>
      <webElementGuid>4e2ab712-70f8-46a9-ad56-d8cf975c8492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halo tes akun,'])[1]/following::p[2]</value>
      <webElementGuid>53a2ed48-ef16-4749-9831-108247e8c9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[4]/following::p[2]</value>
      <webElementGuid>e8706a20-a5fc-406c-a772-66d8442d73bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bioskop'])[5]/preceding::p[2]</value>
      <webElementGuid>62db402b-7b21-47d8-b389-251552ead227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2431']/parent::*</value>
      <webElementGuid>cf83ed71-7103-482d-b0ff-25d830fb2c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/p</value>
      <webElementGuid>4a3ba894-8b51-41ef-966e-91e50b78904d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                        2431
                    ' or . = '
                        2431
                    ')]</value>
      <webElementGuid>fb9b5f58-b89c-476e-bd30-ed9116ffa777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
