<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aktivasi Akun Bioskop Online</name>
   <tag></tag>
   <elementGuidId>5d1defed-0520-4fec-88d3-1a2c89fd63d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div[5]/div[1]/div/table/tbody/tr/td[5]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ca122ca-a286-4650-8944-d99b68cb9573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bqe</value>
      <webElementGuid>c32324d5-51de-4743-86bb-fd4b1b229d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thread-id</name>
      <type>Main</type>
      <value>#thread-f:1755317392702092359</value>
      <webElementGuid>195585f0-8c6a-4e4a-8c7b-01ee1f108859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-thread-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>dba6f7e1-d2b2-4552-ada8-284ae021bcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-message-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>f027860e-7fa7-4ed7-a662-9279b48c2e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legacy-last-non-draft-message-id</name>
      <type>Main</type>
      <value>185c23de5c12b447</value>
      <webElementGuid>9b90d7d5-8870-4450-9020-4c70ae9dcb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktivasi Akun Bioskop Online</value>
      <webElementGuid>8101730f-fedc-475b-93ee-5c2436a21b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:5m&quot;)/span[@class=&quot;bqe&quot;]</value>
      <webElementGuid>0db5063a-49d8-4628-acde-619b168586f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':5m']/span</value>
      <webElementGuid>e6433bb5-0cdf-4b4f-a8b7-6e3a92d76deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[2]/following::span[2]</value>
      <webElementGuid>cf44fd7d-ec6f-4af7-8fa7-03328111ab2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BioskopOnline'])[4]/following::span[2]</value>
      <webElementGuid>5509f775-947f-4cbe-8895-e63f87d776c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktivasi Akun']/parent::*</value>
      <webElementGuid>81079ef9-1c98-4150-b0e6-48b3d3433d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div[2]/span/span</value>
      <webElementGuid>4d60c2d2-cd07-49ce-9921-abe92185e352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Aktivasi Akun Bioskop Online' or . = 'Aktivasi Akun Bioskop Online')]</value>
      <webElementGuid>8c701bef-bc3f-474d-b67c-89008ecfe869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
