<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_to finish signin_password</name>
   <tag></tag>
   <elementGuidId>308ff902-8486-4f0e-8583-459480d63763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-passwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-passwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>519fed82-034c-4c1a-a3e1-004075ddf43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>28ebe6db-4010-4722-b177-4f1431dedd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-passwd</value>
      <webElementGuid>de9bb1bb-fbc1-4335-86b2-6fdd09671ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4c8a1198-47fc-4df1-be23-dac23369080a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8f27c35e-0f05-4deb-aba4-837a6abb3647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>4a15d41e-5757-44e6-a13f-1b71514ebafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid-tracking</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39b97ae2-cb10-4790-a889-e867d020b464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>elm:input;elmt:focus;slk:passwd;mKey:focus-passwd</value>
      <webElementGuid>b3bbab71-4d20-4e37-82e9-652e90db2e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-passwd&quot;)</value>
      <webElementGuid>df2669ff-095d-49bb-9a64-12b4ffeac6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-passwd']</value>
      <webElementGuid>246c46a6-b79a-4155-8127-c638df8a3270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='password-container']/input</value>
      <webElementGuid>bf0b9909-028b-4c07-850b-b5de9cce4d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>20f841ae-74b0-4acd-af4e-6cc1d232b4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'login-passwd' and @name = 'password']</value>
      <webElementGuid>10cef8da-f65a-4ac6-b56d-4ee53732d56b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
