<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ulasan</name>
   <tag></tag>
   <elementGuidId>a81e9925-7cfe-41aa-89ba-b4573807de67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='simple-tab-[object Object]']/span)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38a4e351-7259-48c3-b307-6e5f5c26dc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTab-wrapper</value>
      <webElementGuid>d9676d6f-8b2d-4010-a6a0-29fdc62faeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ulasan</value>
      <webElementGuid>60c6abeb-fb59-4f9f-b9ca-d0853406e0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss91&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;MuiBox-root jss353 MenuBar__MenuBarWrap-sc-24ce6c-0 gIXumC&quot;]/div[@class=&quot;MuiTabs-root MenuBar__StyledTabs-sc-24ce6c-1 dPBFms&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-scrollable&quot;]/div[@class=&quot;MuiTabs-flexContainer&quot;]/button[@id=&quot;simple-tab-[object Object]&quot;]/span[@class=&quot;MuiTab-wrapper&quot;]</value>
      <webElementGuid>82aa4583-e21f-4845-8d69-e20e9cfe76f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='simple-tab-[object Object]']/span)[3]</value>
      <webElementGuid>4e02a001-7ab7-4c6d-9212-cfbbcbe7d630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang'])[1]/following::span[2]</value>
      <webElementGuid>746baf51-5ff2-4977-8839-2a14095db146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekaman'])[1]/following::span[3]</value>
      <webElementGuid>4e4858dc-31e8-4b24-92ea-9114cace3a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskusi'])[1]/preceding::span[4]</value>
      <webElementGuid>73bf29f7-88b2-4c97-bcfd-09057d96f78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ujian Praktek'])[1]/preceding::span[6]</value>
      <webElementGuid>18aad7dd-1e28-4bd3-abd4-36f597228c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ulasan']/parent::*</value>
      <webElementGuid>3b18178f-9dc4-4ff4-b639-7276e0a54348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]/span</value>
      <webElementGuid>fa898778-9c0a-4ff5-a6c5-9b60b5395692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ulasan' or . = 'Ulasan')]</value>
      <webElementGuid>d5a4eda8-fb81-431b-a02d-e44648b5b0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
